name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Scan requirements.txt avec Trivy (non bloquant)
       run: |
        echo "üîç Scan des d√©pendances avec Trivy (requirements.txt)‚Ä¶"

        docker run --rm \
        -v "$PWD":/app \
        -w /app \
        aquasec/trivy:latest fs \
        --scanners vuln \
        --pkg-types library
        --file-patterns "pip:requirements\\.txt" \
        --severity HIGH,CRITICAL \
        --exit-code 0 \
        --format table \
        .

        echo "‚ö†Ô∏è Le pipeline continue m√™me si des vuln√©rabilit√©s sont trouv√©es."
        
  Dockerfile:
   runs-on: ubuntu-latest
   needs: Dependances
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Installer Trivy
       uses: aquasecurity/trivy-action@0.20.0
       with:
         scan-type: fs
         scan-ref: .

     - name: Analyse du Dockerfile avec Trivy
       run: |
         echo "üîç Analyse du Dockerfile (config scan)‚Ä¶"

         trivy config --exit-code 0 --severity HIGH,CRITICAL .

         echo "‚ö†Ô∏è Le pipeline continue m√™me si des probl√®mes sont d√©tect√©s."
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien √† faire ici. Votre application est pr√™te √† √™tre d√©ploy√©e"
