name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer pip-audit
        run: |
          python3 -m pip install --upgrade pip pip-audit

      - name: Contrôler les dépendances (pip-audit)
        run: |
          echo "Analyse des dépendances…"
          pip-audit -r requirements.txt || true
          echo "Des vulnérabilités peuvent être présentes, mais ça continue"
          
      - name: Validation syntaxique du fichier requirements.txt
        run: |
          echo "Vérification syntaxique…"
          pip install -r requirements.txt --dry-run
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer hadolint
        run: |
          sudo apt-get update
          sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: |
          echo "Analyse du Dockerfile"
          hadolint Dockerfile || true
          echo " Des problèmes peuvent être présents, mais le pipeline continue."
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
