name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer pip-audit
        run: |
          python3 -m pip install --upgrade pip pip-audit

      - name: ContrÃ´ler les dÃ©pendances (pip-audit)
        run: |
          echo "Analyse des dÃ©pendancesâ€¦"
          pip-audit -r requirements.txt || true
          echo "âš ï¸ Des vulnÃ©rabilitÃ©s peuvent Ãªtre prÃ©sentes, mais Ã§a continue"
          
      - name: Validation syntaxique du fichier requirements.txt
        run: |
          echo "ğŸ” VÃ©rification syntaxiqueâ€¦"
          pip install -r requirements.txt --dry-run
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Test Dockerfile
        run: |
          echo "ecrire ici le scrypt de contrÃ´le du Dockerfile"
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien Ã  faire ici. Votre application est prÃªte Ã  Ãªtre dÃ©ployÃ©e"
