name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cr√©er le dossier reports
        run: mkdir -p reports

      - name: Scan requirements.txt avec Trivy (rapport + non bloquant)
        run: |
          echo "üîç Scan des d√©pendances avec Trivy (requirements.txt)‚Ä¶"

          docker run --rm -v "$PWD":/app -w /app aquasec/trivy:latest fs \
            --scanners vuln \
            --pkg-types library \
            --file-patterns 'pip:requirements\.txt' \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            --format table \
            /app | tee reports/trivy-deps.txt

          echo "‚ö†Ô∏è Le pipeline continue m√™me si des vuln√©rabilit√©s sont trouv√©es."

      - name: Upload rapport d√©pendances
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports-deps
          path: reports/trivy-deps.txt

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cr√©er le dossier reports
        run: mkdir -p reports

      - name: Analyse du Dockerfile avec Trivy (rapport + non bloquant)
        run: |
          echo "üîç Analyse du Dockerfile (config scan)‚Ä¶"

          docker run --rm -v "$PWD":/app -w /app aquasec/trivy:latest config \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            --format table \
            /app | tee reports/trivy-dockerfile.txt

          echo "‚ö†Ô∏è Le pipeline continue m√™me si des probl√®mes sont d√©tect√©s."

      - name: Upload rapport Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports-dockerfile
          path: reports/trivy-dockerfile.txt

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien √† faire ici. Votre application est pr√™te √† √™tre d√©ploy√©e"
